# Generated by Django 2.1.2 on 2018-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20181213_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='role',
            new_name='roles',
        ),
    ]
