# Generated by Django 2.1.2 on 2018-12-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20181213_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Menu'),
        ),
    ]
